##########
# MAP PAGE
#
# see _data/map-config.csv for field display options
latitude: 46.727485 #to determine center of map
longitude: -117.014185 #to determine center of map
zoom-level: 2 # zoom level for map 
map-base: Esri_WorldStreetMap # set default base map, choose from: Esri_WorldStreetMap, Esri_NatGeoWorldMap, Esri_WorldImagery, OpenStreetMap_Mapnik
map-search: true # true/false, not suggested with large collections
map-search-fuzziness: 0.35 # fuzzy search range from 1 = anything to 0 = exact match only
map-cluster: true # true/false, suggested for large collection or with many items in same location
map-cluster-radius: 25 # size of clusters, from ~ 10 to 80

navbar-color: navbar-dark
# navbar background color
# Choose from bg-primary, bg-secondary, bg-success, bg-danger, bg-warning, bg-info, bg-light, bg-dark, bg-white
navbar-background: bg-dark

# BOOTSWATCH THEMES
# You can replace the standard Bootstrap theme with a Bootswatch (https://github.com/thomaspark/bootswatch) option
# Enter one of the following options below: cerulean; cosmo; cyborg; darkly; flatly; journal; litera; lumen; lux; materia; minty; pulse; sandstone; simplex; sketchy; slate; solar; spacelab; superhero; united; yeti 
bootswatch: # leave blank or comment out for plain bootstrap

# THEME FONTS
base-font-size: 1.2em
text-color: "#191919"
link-color: "#0d6efd"
base-font-family: # comment out for bootstrap defaults. e.g. Roboto
font-cdn: # add font stylesheet, e.g. <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">


